general {
    lock_cmd = pidof hyprlock || hyprlock       # comando ao travar
    before_sleep_cmd = loginctl lock-session    # trava antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # liga monitor ao acordar
}

listener {
    timeout = 480                            # 8 minutos
    on-timeout = loginctl lock-session       # trava a sessão
}

listener {
    timeout = 960                            # 16 minutos
    on-timeout = hyprctl dispatch dpms off   # desliga monitor
    on-resume = hyprctl dispatch dpms on     # liga monitor ao mover mouse
}

#
# listener {
#     timeout = 1800                           # 30 minutos
#     on-timeout = systemctl suspend           # suspende o sistema
# }
